### ISSUE TITLE
update compare

### ISSUE THREAD

**Issue by amitcha06** [Team1690/Scouting-Frontend#371]
This will require a strategy conversation with Omer/Tzury/Oz.
This issue includes: 
- all related gql (aka fetch_compare)
- all related models (for example, compare_classes)
- all related screens/widgets

**Comment by OmerPrag** [comment]
The graphs:
- Points (entire games).
- Teleop points (without ramp).
- Auto ramp levels.
- Endgame ramp levels.
- Total number of cones (sum of teleop and auto).
- Total number of cubes (sum of teleop and auto).

**Comment by amitcha06** [comment]
@OmerPrag does "entire games" mean including ramp or just gamepiece points from entire match?

**Comment by amitcha06** [comment]
![Image](https://user-images.githubusercontent.com/71347633/218508856-e23e7dd1-c030-4711-9225-c86aba908c93.png)

@OmerPrag Last year's Spider Chart. what do we change/keep/delete here

**Comment by OmerPrag** [comment]
Keep nothing - delete this entire bullshit of a chart.

**Comment by amitcha06** [comment]
and srsly now?
