### ISSUE TITLE
update scatter

### ISSUE THREAD

**Issue by amitcha06** [Team1690/Scouting-Frontend#372]
This will require a strategy conversation with Omer/Tzury/Oz.
This issue includes both the fetch, the widget itself, and the screen 
![image](https://user-images.githubusercontent.com/71347633/215852938-1af86f33-62e1-43d6-9610-5ac989a5e147.png)

**Comment by giladwo** [comment]
Or we can talk here with @OmerPrag @ Tzury @ozhuly to save time.
(Not sure if Yoad has an account, but this is easily solvable.)

**Comment by OmerPrag** [comment]
What topic would you like my opinion on exactly?

**Comment by amitcha06** [comment]
As the head of strategy(?), we were hoping to get a specification for the PC view. aka:

A - What do we need to present. do we care about different levels (high/mid/low/missed), modes (tele/auto/combined), point values,  gamepieces....

B - How would you like us to present it. whether it's similar to the old way (specify which data where), or very different (in which case a helpful Paint sketch would be appriciated)

C - Notes, special requests, etc.


@OmerPrag  I commented and tagged you here, but we need this for every screen: #370 #371 #373 #374 #375 (and obviously here too)

The sooner you comment, the sooner we can get to work :)

**Comment by OmerPrag** [comment]
Just do gampiece points (sum of teleop and auto) by the std.
