### ISSUE TITLE
update pick_list

### ISSUE THREAD

**Issue by amitcha06** [Team1690/Scouting-Frontend#373]
This will require a strategy conversation with Omer/Tzury/Oz.
This is a small issue, since it only requires changing the data presented next to each team:
![image](https://user-images.githubusercontent.com/71347633/215853888-4ec48c3c-945e-4ccc-957f-9feef0900b9e.png)
This means changing the "fetch", the mutation, and the picklist widget itself.

**Comment by OmerPrag** [comment]
Changes:
- Ball avg to gamepiece avg.
- Climb points to ramp points.
- Auto balls to auto gamepieces.
- Ball points avg to gamepiece points avg.
- Best climb to can be docked/engaged on the ramp in auto.
Remove:
- Tele aim.
- Auto aim.
Keep:
- Worked/didn't work, didn't come.
- Faults.
- Pit.

**Comment by amitcha06** [comment]
@OmerPrag 
A few questions:
* "Climb points to ramp points." - we have two different balances (auto and endgame), do you want both? combined? only 1?

**Comment by OmerPrag** [comment]
Sorry for not specifying enough...
Ramp points in endgame.
About the "can be engaged...": It supposed to be like the best climb. For example, if last season the best climb you did was to the high rung it said that your best climb is 3. In this season you take the best score from the ramp in the auto period, so if you didn't engaged even once but you've managed to dock, your best ramp score is docked.
