### ISSUE TITLE
Add basic_utill to code to add the option to capitalize the first letter of a String

### ISSUE THREAD

**Issue by ItayNaumann** [Team1690/Scouting-Frontend#401]
this dependency https://github.com/Ephenodrom/Dart-Basic-Utils

**Comment by giladwo** [comment]
Just implement `capitalize`...
This isn't worth the cost of yet another dependency.

If you must, I'd go with a dedicated package like [recase](https://pub.dev/packages/recase).

Still: no need for another dependency here.
