### ISSUE TITLE
Implement Null Safety

### ISSUE THREAD

**Issue by GuyNoimark** [Team1690/Scouting-Frontend#44]
Good for preventing null data being fetched from the database 
https://flutter.dev/docs/null-safety

**Comment by giladwo** [comment]
Has anyone made any progress here?
It shouldn't take more than a few hours, and would noticeably improve compiler-enforced correctness, thus improving maintainability and reducing runtime errors.

**Comment by GuyNoimark** [comment]
I hadn't been able to visit this yet
