### ISSUE TITLE
Determine pit scouting image sizes

### ISSUE THREAD

**Issue by giladwo** [Team1690/Scouting-Frontend#77]
- [x] Update the mockup
- [x] Try some different formats (i.e. jpeg, png, etc.) with good-enough resolutions to check storage requirements.
- [x] Publish results (and mockup link) here

**Comment by GuyNoimark** [comment]
Just finished the mockup, How should I proceed?
https://www.figma.com/file/xpLEcTv3jv0ydCD86eO8qO/Scouting-app?node-id=0%3A1

Should I take a random photo from the TBA?

**Comment by giladwo** [comment]
@itamarsch Can you link your prototype here?
If we're going to use firebase storage (or aws s3 or any other such service) we need to make sure our usage doesn't exceed the free plan.
So if the prototype uses firebase storage, take some pictures (preferably from different phones to have some variance in camera settings) and upload them using the prototype.
Then extrapolate the required storage capacity we need (i.e. if we currently have 3 images that take up 0.8GB and we want 30 per event × 5 events then we need a total of `1.1 * 0.8 * 30/3 * 5` GB (with some extra to make sure we're not too close to the cap)) and make sure it's still in the free plan cap.

**Comment by itamarsch** [comment]
We made a new branch called mutations/pit_scouting/firebase where we
implemented firebase storage with the current pitview and everything worked
great. firebase storage has 10Gb and from what I saw a regular jpg image
from my phone was 2.5~ so storage will certainly not be a problem

**Comment by giladwo** [comment]
Just putting the link here #80
